version: '2'
services:
  # Fusio container
  fusio:
    image: fusio/fusio
    environment:
      FUSIO_PROJECT_KEY: "42eec18ffdbffc9fda6110dcc705d6ce"
      FUSIO_HOST: "localhost"
      FUSIO_URL: "http://localhost"
      FUSIO_APPS_URL: "http://apps.localhost"
      FUSIO_ENV: "prod"
      FUSIO_DB_NAME: "fusio"
      FUSIO_DB_USER: "fusio"
      FUSIO_DB_PW: "61ad6c605975"
      FUSIO_DB_HOST: "mysql_fusio"
      FUSIO_BACKEND_USER: "demo"
      FUSIO_BACKEND_EMAIL: "demo@fusio-project.org"
      FUSIO_BACKEND_PW: "75dafcb12c4f"
      FUSIO_VERSION: "master"
      PROVIDER_FACEBOOK_KEY: ""
      PROVIDER_FACEBOOK_SECRET: ""
      PROVIDER_GOOGLE_KEY: ""
      PROVIDER_GOOGLE_SECRET: ""
      PROVIDER_GITHUB_KEY: ""
      PROVIDER_GITHUB_SECRET: ""
      RECAPTCHA_KEY: ""
      RECAPTCHA_SECRET: ""
    links:
      - mysql_fusio
    ports:
      - "80:8080"
    volumes:
      - ./apps:/var/www/html/fusio/apps
      - ./public:/var/www/html/fusio/public

  # Fusio system database
  mysql_fusio:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "7f3e5186032a"
      MYSQL_USER: "fusio"
      MYSQL_PASSWORD: "61ad6c605975"
      MYSQL_DATABASE: "fusio"
    volumes:
      - ./db:/var/lib/mysql
